### PR TITLE
DM-26988: Update TE1, TE2 metrics and add TE3,TE4 metrics

### PR DESCRIPTION
**Pull request by bechtol**
This PR updates ellipticity residual correlation metrics based on discussions at the virtual DM F2F meeting in Feb 2021. There are several notable changes:

1. TE1 and TE2 were previously computed from matched single-visit catalogs. Now TE1 and TE2 are computed from deep coadd. 
2. TE3 and TE4 are similar to TE1 and TE2, and use the same underlying mathematical operations, but are measured on individual visits. This PR adds TE3 and TE4.
3. Utility functions for computing correlation functions involving ellipticity residuals have been ported from `pipe_analysis`. The implementation in `pipe_analysis` was done in a general way that allows all of the rho statistics to be computed. The various rho statistics and particular range of angular scales can now be easily selected in configuration. In other words, it should be straightforward to compute all the rho statistics now.
4. Added a function to merge the individual detector catalogs (for visits) and individual patch catalogs (for tracts). This function also applies the photometric and astrometric calibrations from the associated photo_calib and wcs of each input catalog. This function should probably be modified slightly to make the photometric and astrometric calibrations optional. Something to consider here is that the run methods of many measurement tasks will now be taking in multiple data arguments (e.g., catalogs, photo_calibs, astrom_calibs) as well as metric name, and sometimes dataIds. This is because I think we want to be somewhat flexible with how the merging and calibration is done, allowing this to be set in configuration, rather than in the run or runQuantum method of the base class that calls the run method of the specific measurement task. My preference would be to have a convention that puts the metric name as the first argument, rather than as a second or third argument, as currently seems to be the case for many of the measurement tasks.

Things I would still like to do:
- Add a function for applying basic selections (e.g., fully deblended, PSF-like, SNR threshold, quality flags) to catalogs. I'd like to pull out this general functionality since it will likely be applied for many metrics.
- Add option to use distortion or shear convention for ellipticity calculation

Still to be done:
- Add unit tests
- Apply to some larger test dataset such RC2 to have more statistics to gauge performance
- It's likely the current changes broke something in WPerp calculation. Need to check.

### CODE REVIEW

**Comment by leannep** [comment]
Adding an option to use distortion or shear convention is good. I think the distortion convention is currently in place. We should keep this and implement the (now more commonly used) shear convention in the next iteration

**Comment by leannep** [comment]
Application to some larger test dataset is something that we can do for all metrics we are updating to the current iteration in one run. RC2 would be good.

**Comment by bechtol** [comment]
Added unit tests. Added option to use shear ellipticity convention. Now using camelCase consistently. Now passing scons.

Discussed with @leannep to make a separate ticket to create a function to apply basic selection criteria for bright well measured stars consistently across metrics.

**Review by jeffcarlin — APPROVED** [review]
Overall this looks great! I won't engage specifically with the algorithms to calculate rho statistics, but will assume they are calculating the "right thing." 

Note that since you have implemented all rho statistics, you can probably set DM-29406 ("Implement the full set of Rowe statistics") to "Invalid."

If the `mergeCatalogs` functionality is fixing a more general issue, we should perhaps create a separate ticket to update that in other Tasks (where appropriate)?

I definitely agree that the quality flag cuts that are being applied (to the gri bands only!) in `matcher` should be (a) updated, and (b) refactored into a separate module to allow them to be configurable (like `filterMatches`).

There was an issue with treecorr giving different results on different platforms. Simon implemented an option to make it consistent across platforms ([https://github.com/lsst/faro/pull/71](https://github.com/lsst/faro/pull/71)), but the intention was to have it an optional switch. Can you confirm that merging this ticket will retain that option (and therefore not break `validate_drp_gen3`)?

Otherwise, all looks good to merge.

**Pull request merged**
