### PR TITLE
Fix units error in AB1.

### PR DESCRIPTION
**Pull request by jeffcarlin**

### CODE REVIEW

**Comment by bechtol** [comment]
Thanks @jeffcarlin . I'm wondering whether we expect that this modification should have caused an assertion error during the AB1 unit test. There is a test for AB1 and the assertEqual call is sensitive to units. The comparison data is at faro/tests/data/AB1_design_expected_0_70_i.yaml, for example.

**Comment by jeffcarlin** [comment]
Ack - I forgot to run `scons`. You are correct that it made the unit test fail -- I'll update the unit test as well.

**Comment by jeffcarlin** [comment]
Unit test updated, and `scons` now successfully runs. Good catch @bechtol !

**Review by bechtol — APPROVED** [review]
Thanks for updating the test data results for consistency. Looks good to me.

**Pull request merged**
