### PR TITLE
Tickets/dm 30448

### PR DESCRIPTION
**Pull request by jeffcarlin**
Small change to change the shape measurements targeted by TEx algorithms.

### CODE REVIEW

**Review by bechtol — APPROVED** [review]
Thanks for this change, and for all the detective work to track down the issue. 

For the record, there is further discussion of the motivation for the change at [DM-30359](https://jira.lsstcorp.org/browse/DM-30359).

**Comment by timj** [comment]
@jeffcarlin do you intend for that merge commit to be in this PR?

**Comment by jeffcarlin** [comment]
> @jeffcarlin do you intend for that merge commit to be in this PR?

I don't suppose I do. I didn't notice it was there. (Also not sure how to remove it...)

**Comment by timj** [comment]
`git rebase` should fix it fine. If you can't work it out you can slack me and we can go through it together.

**Comment by jeffcarlin** [comment]
I just did a rebase, and was about to push the merge. I'll see if I can sort out whether the rebase squashed that previous merge.

**Pull request closed without merging**
